### ISSUE TITLE
Panic on first use, discovery.go:43

### ISSUE THREAD

**Issue by rfay** [jondot/autobrew#1]
I only got to the very beginning, with `brew tap jondot/autobrew && brew install autobrew` and then disaster...

```
$ autobrew --user rfay --project=ddev --tap=homebrew-ddev
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1396834]

goroutine 1 [running]:
main.findOSXRelease(0x0, 0x15108a0, 0xc00007c008, 0x7ffeefbff610)
	/Users/dotan.nahum/experiments/autobrew/discovery.go:43 +0x94
main.(*Discovery).Discover(0xc0000bbf00, 0x28, 0x7ffeefbff610, 0x4)
	/Users/dotan.nahum/experiments/autobrew/discovery.go:65 +0x107
main.main()
	/Users/dotan.nahum/experiments/autobrew/main.go:33 +0x1f1
```

**Comment by maxandersen** [comment]
I see exact same error.
